---
title: "Supplemental Figures Draft"
author: "Andreea Murariu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
#load datasets
load("~/Documents/github/ext_analysis/immuno.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/immuno.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/immuno.data.limma.Rda")
load("~/Documents/github/ext_analysis/immuno.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/immuno.data.edger.Rda")

load("~/Documents/github/ext_analysis/brca.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/brca.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/brca.data.limma.Rda")
load("~/Documents/github/ext_analysis/brca.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/brca.data.edger.Rda")

load("~/Documents/github/ext_analysis/kirc.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/kirc.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/kirc.data.limma.Rda")
load("~/Documents/github/ext_analysis/kirc.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/kirc.data.edger.Rda")

load("~/Documents/github/ext_analysis/lihc.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/lihc.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/lihc.data.limma.Rda")
load("~/Documents/github/ext_analysis/lihc.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/lihc.data.edger.Rda")

load("~/Documents/github/ext_analysis/luad.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/luad.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/luad.data.limma.Rda")
load("~/Documents/github/ext_analysis/luad.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/luad.data.edger.Rda")

load("~/Documents/github/ext_analysis/prad.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/prad.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/prad.data.limma.Rda")
load("~/Documents/github/ext_analysis/prad.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/prad.data.edger.Rda")

load("~/Documents/github/ext_analysis/thca.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/thca.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/thca.data.limma.Rda")
load("~/Documents/github/ext_analysis/thca.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/thca.data.edger.Rda")


load("~/Documents/github/ext_analysis/mts.data.aldex2_0.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex2_1.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex2_2.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex2_5.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex3_0.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex3_1.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex3_2.Rda")
load("~/Documents/github/ext_analysis/mts.data.aldex3_5.Rda")
load ("~/Documents/github/ext_analysis/mts.data.limma.Rda")
load("~/Documents/github/ext_analysis/mts.data.deseq.Rda") 
load("~/Documents/github/ext_analysis/mts.data.edger.Rda")

```

```{r}
#calculations for diff between plots - difference between ALDEx2 and ALDEx3

source('~/Documents/github/usri/code/graph.diff.fun.R')
graph.diff.fun(immuno.data_0.aldex2, immuno.data_0.aldex3)


source('~/Documents/github/usri/code/graph.diff.fun.R')

graph2.fun(DESeq_var = kirc.data.DESeq, edgeR_var = kirc.data.edgeR, limma_var = kirc.data.limma, aldex_0_var = kirc.data_0.aldex2, aldex_1_var = kirc.data_1.aldex2, aldex_2_var = kirc.data_2.aldex2, aldex_5_var = kirc.data_5.aldex2, aldex3_0_var = kirc.data_0.aldex3, aldex3_1_var = kirc.data_1.aldex3, aldex3_2_var = kirc.data_2.aldex3, aldex3_5_var = kirc.data_5.aldex3)

graph2.fun(DESeq_var = mts.data.DESeq, edgeR_var = mts.data.edgeR, limma_var = mts.data.limma, aldex_0_var = mts.data_0.aldex2, aldex_1_var = mts.data_1.aldex2, aldex_2_var = mts.data_2.aldex2, aldex_5_var = mts.data_5.aldex2, aldex3_0_var = mts.data_0.aldex3, aldex3_1_var = mts.data_1.aldex3, aldex3_2_var = mts.data_2.aldex3, aldex3_5_var = mts.data_5.aldex3)

```

```{r}
#plots containing limma, DESeq, edgeR, ALDEx2, and ALDEx3
#sample code, 2 panel plotting the tools with a 0.5 fold change cutoff
source('~/Documents/github/usri/code/graph2.fun.R')
  
graph2.fun(DESeq_var = immuno.data.DESeq, edgeR_var = immuno.data.edgeR, limma_var = immuno.data.limma, aldex_0_var = immuno.data_0.aldex2, aldex_1_var = immuno.data_1.aldex2, aldex_2_var = immuno.data_2.aldex2, aldex_5_var = immuno.data_5.aldex2, aldex3_0_var = immuno.data_0.aldex3, aldex3_1_var = immuno.data_1.aldex3, aldex3_2_var = immuno.data_2.aldex3, aldex3_5_var = immuno.data_5.aldex3)
```

```{r}
graph.fun(DESeq_var = cdiff.data.DESeq, edgeR_var = cdiff.data.edgeR, limma_var = cdiff.data.limma, aldex_0_var = cdiff.data_0.aldex2, aldex_1_var = cdiff.data_1.aldex2, aldex_2_var = cdiff.data_2.aldex2, aldex_5_var = cdiff.data_5.aldex2, aldex3_0_var = cdiff.data_0.aldex3, aldex3_1_var = cdiff.data_1.aldex3, aldex3_2_var = cdiff.data_2.aldex3, aldex3_5_var = cdiff.data_5.aldex3)

```

